### ISSUE TITLE
Move to IMSGlobal github?

### ISSUE THREAD

**Issue by bluej100** [pfgray/basiclti-util-java#5]
What would you think of moving this project into https://github.com/IMSGlobal , especially since you and I are both members? I imagine that will make @LMattson happier about our using the org.imsglobal namespace.

**Comment by pfgray** [comment]
Yes, I always imagined that this would eventually end up there. I just emailed IMS Global, and with their approval, I'll transfer this repo over there, along with all issues/commits,
thanks Braden!

**Comment by bluej100** [comment]
No response?

**Comment by LMattson** [comment]
Hi-

I sent for form to sign last week to Paul, I haven’t heard back.

lisa

**Comment by bluej100** [comment]
Thanks, Lisa.

**Comment by pfgray** [comment]
Yeah sorry, I haven't had time to read the form & sign it, I've been very busy.

I'll try and do that this week, thanks!

**Comment by bluej100** [comment]
Ping.

**Comment by LMattson** [comment]
Hi Braden-

This was done several weeks ago.

https://github.com/IMSGlobal/basiclti-util-java

Lisa

**Comment by bluej100** [comment]
Oh, I apologize.
